var data=[
["Silver Lake","americanforklake.jpg",""],
["Buffalo Peak","BUffalo.jpg"],
["The Crater","Crater.jpg"],
["Diamond Fork Hot Spring","diamondfork.jpg"],
["The shoes","feet.jpg"],
["Bridal Veil","bridalveil.jpg"],
["Hot Spring","fillmore.jpg"],
["Corgi Hot Spring","fivehotspring.jpg"],
["Utah Lake","Lake.jpg"],
["Mona Rope Swing","Mona.jpg"],
["Alpine Loop","Mountain.jpg"],
["Mount Timpanogos","mountimp.jpg"],
["Mount Timpanogos","mountimp2.jpg"],
["Payson Lake","paysonlake.jpg"],
["Provo Canyon","provocanyon.jpg"],
["Provo Canyon","provocanyoncliff.jpg"],
["Provo Library","provolibrary.jpg"],
["Provo River","provoriver.jpg"],
["Rock Canyon","rockdog.jpg"],
["Rock Canyon Park","rockpark.jpg"],
["Shave Ice","shaveicecream.jpg"],
["Silver Lake","silverlake2.jpg"],
["Sodalicious","sodalicious.jpg"],
["Squaw Peak Overlook","squawpeak.jpg"],
["Squaw Peak","squakpeak.jpg"],
["Waffle Love","wafflelove.jpg"],
["Stewart Falls","waterfall.jpg"],
["Y Mountain","ymountain.jpg"],
]
module.exports=data;
